### ISSUE TITLE
Extracted code is not identifying specific coding syntax (i.e, indentation, etc...)

### ISSUE THREAD

**Issue by Nathan-Bransby-NMT** [NM-TAFE/dip-programming-prj-advanced-gui-evolve#4]
When the code is being extracted, specific coding syntax is not being detected.

an example of this would be:

```python
def greetings():
print("hello")
```

... where the indentation of the python syntax is not being recognised.

**Comment by rafrafavi** [comment]
I have removed the good first issue label as I think this is not appropriate for Cert IV handling - also ensure you include more detail with the issue. As, as written, it would be very difficult to reproduce. 

Consider: what does not recognized mean? Do you mean when you have indentation in the code the OCR doesn't detect it? Where in the code are the OCR settings specified? Are you sure this is true of every conceivable example of code?
